/**
 * Rewrites the "Running totals" table in docs/costs.md from the usage logs the code keeps in
 * data/demo/usage/ (Gemma calls and neurons, SerpApi searches, the Tinker ledger) and the
 * recorded TabPFN responses in ranker/fixtures/. Run before every paid or rate-limited call
 * and after each milestone: pnpm costs
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { repoRoot } from "@roundtrip/core/server-env";

const ROOT = repoRoot();
const usage = (f: string) => join(ROOT, "data/demo/usage", f);
const jsonl = <T>(f: string): T[] =>
  readFileSync(usage(f), "utf8")
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l) as T);

interface GemmaCall {
  service: string;
  cached: boolean;
  ok: boolean;
  neurons?: number;
}
const gemma = jsonl<GemmaCall>("gemma-calls.jsonl").filter((c) => !c.cached);
const cf = gemma.filter((c) => c.service === "cloudflare");
const or = gemma.filter((c) => c.service.startsWith("openrouter"));
const neuronsByDay = JSON.parse(readFileSync(usage("neurons-by-day.json"), "utf8")) as Record<string, number>;
const busiest = Object.entries(neuronsByDay).sort((a, b) => b[1] - a[1])[0];

const serp = JSON.parse(readFileSync(usage("serpapi.json"), "utf8")) as { liveSearches: number };
const tinker = jsonl<{ costUsd?: number; promptTokens?: number; completionTokens?: number }>("tinker-ledger.jsonl");
const tinkerUsd = tinker.reduce((s, t) => s + (t.costUsd ?? 0), 0);
const tinkerTokens = tinker.reduce((s, t) => s + (t.promptTokens ?? 0) + (t.completionTokens ?? 0), 0);
const tabpfn = readdirSync(join(ROOT, "ranker/fixtures")).filter((f) => f.endsWith(".json")).length;

const n = (x: number) => x.toLocaleString("en-US", { maximumFractionDigits: 0 });
const table = [
  "| Service | Units used | Estimated cost |",
  "|---|---|---|",
  `| Tinker | ${n(tinkerTokens)} tokens in ${tinker.length} calls | $${tinkerUsd.toFixed(2)} of MAX_TINKER_SPEND_USD |`,
  `| SerpApi | ${serp.liveSearches} live searches of SERPAPI_MAX_SEARCHES | $0.00 (free plan) |`,
  "| ElevenLabs | 0 characters | $0.00 (free plan) |",
  `| Cloudflare Workers AI | ${cf.length} calls, ${n(Object.values(neuronsByDay).reduce((a, b) => a + b, 0))} neurons; busiest day ${busiest ? `${busiest[0]}, ${n(busiest[1])} of 10,000` : "none"} | $0.00 (free plan) |`,
  `| OpenRouter | ${or.length} requests, ${or.filter((c) => c.ok).length} answered | $0.00 (free models) |`,
  `| TabPFN | ${tabpfn} recorded predictions (ranker/fixtures) | $0.00 (free pools) |`,
].join("\n");

const path = join(ROOT, "docs/costs.md");
const doc = readFileSync(path, "utf8");
const start = doc.indexOf("## Running totals");
if (start < 0) throw new Error("docs/costs.md has no Running totals section");
const after = doc.indexOf("\n## ", start + 5);
const section = `## Running totals\n\nGenerated by \`pnpm costs\` from data/demo/usage/ and ranker/fixtures/.\n\n${table}\n`;
writeFileSync(path, doc.slice(0, start) + section + (after >= 0 ? doc.slice(after) : ""), "utf8");
console.log(table);
