/**
 * Builds 40 synthetic event listings from known attributes, in the style of Google's events
 * results, and saves the attributes as ground truth in evals/events-labeled.json.
 * Everything here is synthetic. Run: pnpm --filter @roundtrip/scripts exec tsx gen-events.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { repoRoot } from "@roundtrip/core/server-env";

type Cat =
  | "festival"
  | "association_meeting"
  | "film_screening"
  | "religious"
  | "senior_program"
  | "library_program"
  | "conversation_circle"
  | "walking_group"
  | "market"
  | "class"
  | "volunteering"
  | "music_dance"
  | "talk"
  | "other";

interface Spec {
  title: string;
  venue: string;
  address: string;
  about: string;
  /** day of the week Mon 5 Oct to Sun 11 Oct 2026, or null for no time given */
  day: number | null;
  start?: string;
  end?: string;
  price: number | "free";
  languageMatch: 0 | 1 | 2;
  suitsOlderAdults: boolean;
  indoor: boolean | null;
  category: Cat;
}

const S: Spec[] = [
  {
    title: "Bathukamma celebration",
    venue: "Fremont community hall",
    address: "3300 Capitol Ave, Fremont, CA",
    about: "The Telugu association invites families to build and celebrate Bathukamma with songs and dinner.",
    day: 6,
    start: "16:00",
    end: "20:00",
    price: "free",
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: true,
    category: "festival",
  },
  {
    title: "Telugu Association monthly meeting",
    venue: "India Community Center",
    address: "525 Los Coches St, Milpitas, CA",
    about: "Members meet to plan Sankranti and welcome newcomers. Telugu spoken.",
    day: 3,
    start: "18:30",
    end: "20:00",
    price: "free",
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: true,
    category: "association_meeting",
  },
  {
    title: "Telugu movie night: family drama with English subtitles",
    venue: "Cinemark Fremont",
    address: "39160 Paseo Padre Pkwy, Fremont, CA",
    about: "A new Telugu family film. All ages.",
    day: 6,
    start: "15:00",
    end: "17:45",
    price: 14,
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: true,
    category: "film_screening",
  },
  {
    title: "Annamacharya keerthana evening",
    venue: "Sri Venkateswara temple hall",
    address: "Livermore, CA",
    about: "Devotional Telugu songs by local singers. Prasadam served.",
    day: 5,
    start: "18:00",
    end: "19:30",
    price: "free",
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: true,
    category: "religious",
  },
  {
    title: "Telugu book club: Yandamuri novels",
    venue: "Fremont Main Library, meeting room B",
    address: "2400 Stevenson Blvd, Fremont, CA",
    about: "Readers discuss a Telugu novel. Tea provided.",
    day: 2,
    start: "10:30",
    end: "12:00",
    price: "free",
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: true,
    category: "library_program",
  },
  {
    title: "Telugu walking group at Lake Elizabeth",
    venue: "Lake Elizabeth, Central Park",
    address: "40000 Paseo Padre Pkwy, Fremont, CA",
    about: "Telugu-speaking seniors walk the lake loop together, slow pace.",
    day: 0,
    start: "07:30",
    end: "08:30",
    price: "free",
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: false,
    category: "walking_group",
  },
  {
    title: "Ugadi pachadi cooking class",
    venue: "Shiva Murugan Temple kitchen",
    address: "Concord, CA",
    about: "Learn the Telugu new year dish in Telugu and English.",
    day: 4,
    start: "11:00",
    end: "12:30",
    price: 10,
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: true,
    category: "class",
  },
  {
    title: "Telugu poetry recital and talk",
    venue: "Milpitas Library",
    address: "160 N Main St, Milpitas, CA",
    about: "A retired professor reads Sri Sri and takes questions.",
    day: 1,
    start: "14:00",
    end: "15:30",
    price: "free",
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: true,
    category: "talk",
  },
  {
    title: "Telugu youth DJ night",
    venue: "Opal Social Club",
    address: "Santa Clara, CA",
    about: "Tollywood hits, 21+, cover charge at the door.",
    day: 5,
    start: "22:00",
    end: "02:00",
    price: 25,
    languageMatch: 2,
    suitsOlderAdults: false,
    indoor: true,
    category: "music_dance",
  },
  {
    title: "Sankranti muggulu contest",
    venue: "Central Park picnic area",
    address: "Fremont, CA",
    about: "Rangoli contest on the lawn, prizes for all ages.",
    day: 6,
    start: "10:00",
    end: "13:00",
    price: "free",
    languageMatch: 2,
    suitsOlderAdults: true,
    indoor: false,
    category: "festival",
  },
  {
    title: "Sanskriti Durga Puja",
    venue: "Fremont Hindu Temple",
    address: "3676 Delaware Dr, Fremont, CA",
    about: "Bengali community puja, aarti and bhog. Everyone welcome.",
    day: 4,
    start: "17:30",
    end: "21:00",
    price: "free",
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: true,
    category: "religious",
  },
  {
    title: "Diwali mela",
    venue: "Fremont Hub plaza",
    address: "39281 Fremont Hub, Fremont, CA",
    about: "Outdoor stalls, sweets and lamps. Free entry.",
    day: 6,
    start: "12:00",
    end: "18:00",
    price: "free",
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: false,
    category: "festival",
  },
  {
    title: "Navratri garba night",
    venue: "Santa Clara Convention Center",
    address: "5001 Great America Pkwy, Santa Clara, CA",
    about: "Garba and dandiya with live music. Tickets required.",
    day: 5,
    start: "19:30",
    end: "23:30",
    price: 20,
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: true,
    category: "music_dance",
  },
  {
    title: "Hindi poetry evening (kavi sammelan)",
    venue: "ICC hall",
    address: "525 Los Coches St, Milpitas, CA",
    about: "Poets read in Hindi and Urdu.",
    day: 3,
    start: "17:00",
    end: "19:00",
    price: 5,
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: true,
    category: "talk",
  },
  {
    title: "Bollywood dance class for beginners",
    venue: "Dance studio on Mowry Ave",
    address: "Mowry Ave, Fremont, CA",
    about: "Drop-in class, all ages welcome.",
    day: 1,
    start: "19:00",
    end: "20:00",
    price: 15,
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: true,
    category: "class",
  },
  {
    title: "Tamil cultural fair",
    venue: "Newark Community Center",
    address: "35501 Cedar Blvd, Newark, CA",
    about: "Food, music and crafts from Tamil Nadu.",
    day: 6,
    start: "11:00",
    end: "16:00",
    price: "free",
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: true,
    category: "festival",
  },
  {
    title: "Punjabi bhangra night",
    venue: "Morni Lounge",
    address: "San Jose, CA",
    about: "Bhangra DJ, bar open, 21 and over.",
    day: 5,
    start: "21:30",
    end: "01:30",
    price: 30,
    languageMatch: 1,
    suitsOlderAdults: false,
    indoor: true,
    category: "music_dance",
  },
  {
    title: "Gujarati samaj potluck",
    venue: "Quarry Lakes picnic site",
    address: "2100 Isherwood Way, Fremont, CA",
    about: "Bring a dish, games for children and elders.",
    day: 7,
    start: "12:00",
    end: "15:00",
    price: "free",
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: false,
    category: "other",
  },
  {
    title: "Bengali film screening",
    venue: "Fremont Main Library auditorium",
    address: "2400 Stevenson Blvd, Fremont, CA",
    about: "Satyajit Ray classic with English subtitles.",
    day: 3,
    start: "14:00",
    end: "16:00",
    price: "free",
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: true,
    category: "film_screening",
  },
  {
    title: "Volunteer morning at the temple kitchen",
    venue: "Fremont Hindu Temple",
    address: "3676 Delaware Dr, Fremont, CA",
    about: "Help prepare annadanam. Ask at the office to sign up.",
    day: 2,
    start: "09:00",
    end: "11:30",
    price: "free",
    languageMatch: 1,
    suitsOlderAdults: true,
    indoor: true,
    category: "volunteering",
  },
  {
    title: "Irvington farmers market",
    venue: "Irvington district",
    address: "Bay St, Fremont, CA",
    about: "Fresh produce in the open air every Sunday.",
    day: 7,
    start: "09:00",
    end: "13:00",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "market",
  },
  {
    title: "English conversation circle for newcomers",
    venue: "Fremont Main Library",
    address: "2400 Stevenson Blvd, Fremont, CA",
    about: "Practice everyday English with volunteers. All levels.",
    day: 3,
    start: "10:30",
    end: "11:30",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: true,
    category: "conversation_circle",
  },
  {
    title: "Chair yoga for seniors",
    venue: "Age Well Center at Lake Elizabeth",
    address: "40086 Paseo Padre Pkwy, Fremont, CA",
    about: "Gentle seated yoga. Free for members, $3 drop-in.",
    day: 2,
    start: "10:00",
    end: "11:00",
    price: 3,
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: true,
    category: "senior_program",
  },
  {
    title: "Community garden volunteer day",
    venue: "Fremont community garden",
    address: "Fremont, CA",
    about: "Weed, water and harvest. Gloves provided.",
    day: 6,
    start: "09:00",
    end: "11:00",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "volunteering",
  },
  {
    title: "Salsa night at the lounge",
    venue: "Latin Lounge",
    address: "Fremont, CA",
    about: "Dance till late. Bar open. 21+.",
    day: 5,
    start: "21:00",
    end: "01:00",
    price: 15,
    languageMatch: 0,
    suitsOlderAdults: false,
    indoor: true,
    category: "music_dance",
  },
  {
    title: "Charity 5K run",
    venue: "Central Park",
    address: "Fremont, CA",
    about: "Timed 5K race, registration required.",
    day: 6,
    start: "07:00",
    end: "09:30",
    price: 35,
    languageMatch: 0,
    suitsOlderAdults: false,
    indoor: false,
    category: "other",
  },
  {
    title: "Jazz at the plaza",
    venue: "Niles Town Plaza",
    address: "37592 Niles Blvd, Fremont, CA",
    about: "Free outdoor concert, bring a chair.",
    day: 6,
    start: "12:00",
    end: "14:00",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "music_dance",
  },
  {
    title: "Museum free day",
    venue: "Museum of Local History",
    address: "190 Anza St, Fremont, CA",
    about: "Free admission for all visitors.",
    day: 7,
    start: "11:00",
    end: "16:00",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: true,
    category: "other",
  },
  {
    title: "Toddler story time",
    venue: "Centerville Library",
    address: "3801 Nicolet Ave, Fremont, CA",
    about: "Songs and stories for children ages 1 to 3 with a caregiver.",
    day: 2,
    start: "10:00",
    end: "10:30",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: false,
    indoor: true,
    category: "library_program",
  },
  {
    title: "Watercolor class for adults",
    venue: "Olive Hyde Art Gallery",
    address: "123 Washington Blvd, Fremont, CA",
    about: "Beginner class, materials included.",
    day: 4,
    start: "13:30",
    end: "15:30",
    price: 40,
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: true,
    category: "class",
  },
  {
    title: "Morning walking club",
    venue: "Coyote Hills Regional Park",
    address: "8000 Patterson Ranch Rd, Fremont, CA",
    about: "Easy two-mile loop on paved paths, every weekday.",
    day: 1,
    start: "08:00",
    end: "09:00",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "walking_group",
  },
  {
    title: "Medicare basics talk",
    venue: "Age Well Center at Lake Elizabeth",
    address: "40086 Paseo Padre Pkwy, Fremont, CA",
    about: "A counselor explains Medicare options. Q&A after.",
    day: 4,
    start: "10:00",
    end: "11:30",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: true,
    category: "talk",
  },
  {
    title: "Flea market and car meet",
    venue: "Ohlone College parking lot",
    address: "43600 Mission Blvd, Fremont, CA",
    about: "Vendors and classic cars, open air.",
    day: 6,
    start: "09:00",
    end: "15:00",
    price: 2,
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "market",
  },
  {
    title: "Cribbage club",
    venue: "New Pizza Italia",
    address: "Fremont, CA",
    about: "Friendly cribbage, singles and doubles.",
    day: 6,
    start: "10:00",
    end: "12:00",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: true,
    category: "other",
  },
  {
    title: "Craft beer festival",
    venue: "Downtown plaza",
    address: "Fremont, CA",
    about: "Tastings from local breweries. ID required.",
    day: 6,
    start: "14:00",
    end: "19:00",
    price: 45,
    languageMatch: 0,
    suitsOlderAdults: false,
    indoor: false,
    category: "festival",
  },
  {
    title: "Library tech help for seniors",
    venue: "Irvington Library",
    address: "41825 Greenpark Dr, Fremont, CA",
    about: "Bring your phone; volunteers help with apps and video calls.",
    day: 5,
    start: "14:00",
    end: "16:00",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: true,
    category: "library_program",
  },
  {
    title: "Tai chi in the park",
    venue: "Lake Elizabeth lawn",
    address: "Fremont, CA",
    about: "Slow tai chi practice for all ages, outdoors.",
    day: 3,
    start: "08:30",
    end: "09:30",
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "class",
  },
  {
    title: "Gardening workshop: winter vegetables",
    venue: "Fremont community garden shed",
    address: "Fremont, CA",
    about: "Hands-on workshop. Sign up at the door.",
    day: 7,
    start: "10:00",
    end: "11:30",
    price: 5,
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "class",
  },
  {
    title: "Neighborhood cleanup",
    venue: "Meet at the community center",
    address: "Fremont, CA",
    about: "Volunteers pick up litter on nearby streets. Date to be announced.",
    day: null,
    price: "free",
    languageMatch: 0,
    suitsOlderAdults: true,
    indoor: false,
    category: "volunteering",
  },
  {
    title: "Open mic comedy",
    venue: "The Basement Bar",
    address: "San Jose, CA",
    about: "Late-night stand-up. 18+.",
    day: 5,
    start: "22:30",
    end: "00:30",
    price: 10,
    languageMatch: 0,
    suitsOlderAdults: false,
    indoor: true,
    category: "other",
  },
];

const DAYS = ["Mon, Oct 5", "Tue, Oct 6", "Wed, Oct 7", "Thu, Oct 8", "Fri, Oct 9", "Sat, Oct 10", "Sun, Oct 11"];
const ISO_DAY = ["2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"];

const ampm = (t: string) => {
  const [h, m] = t.split(":").map(Number) as [number, number];
  const hh = h % 12 === 0 ? 12 : h % 12;
  return `${hh}${m ? `:${String(m).padStart(2, "0")}` : ""} ${h < 12 ? "AM" : "PM"}`;
};

function iso(day: number, time: string, next = false): string {
  const base = ISO_DAY[day - 1]!;
  if (!next) return `${base}T${time}:00-07:00`;
  const d = new Date(`${base}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + 1);
  return `${d.toISOString().slice(0, 10)}T${time}:00-07:00`;
}

const items = S.map((s, i) => {
  const when = s.day ? `${DAYS[s.day - 1]}, ${ampm(s.start!)} – ${ampm(s.end!)}` : "";
  const tickets = s.price === "free" ? "Free" : `$${s.price}`;
  const text = [
    s.title,
    when && `When: ${when}`,
    `Where: ${s.venue}`,
    `Address: ${s.address}`,
    `About: ${s.about}`,
    `Tickets: ${tickets}`,
  ]
    .filter(Boolean)
    .join("\n");
  const endsNextDay = s.end && s.start && s.end < s.start;
  return {
    id: `ev${String(i + 1).padStart(2, "0")}`,
    listing: text,
    truth: {
      languageMatch: s.languageMatch,
      suitsOlderAdults: s.suitsOlderAdults,
      indoor: s.indoor,
      cost: { free: s.price === "free", amount: s.price === "free" ? 0 : s.price, currency: "USD" },
      category: s.category,
      start: s.day ? iso(s.day, s.start!) : null,
      end: s.day ? iso(s.day, s.end!, Boolean(endsNextDay)) : null,
    },
  };
});

writeFileSync(
  join(repoRoot(), "evals/events-labeled.json"),
  `${JSON.stringify(
    {
      provenance: "synthetic",
      note: "40 synthetic listings built from known attributes; truth is the attributes they were built from.",
      week: "Monday 2026-10-05 to Sunday 2026-10-11",
      offset: "-07:00",
      items,
    },
    null,
    1,
  )}\n`,
  "utf8",
);
console.log(`Wrote ${items.length} labeled listings.`);
